In [1]:
import pandas as pd

In [2]:
movies_df= pd.read_csv('D:\ML\Krish Naik Codes\Codebasics\datasets\movies.csv')

In [3]:
movies_df.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [4]:
rating_df= pd.read_csv(r'D:\ML\Krish Naik Codes\Codebasics\datasets\ratings.csv')

In [5]:
rating_df.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [6]:
movies_df.shape

(9742, 3)

In [7]:
rating_df.shape

(100836, 4)

In [9]:
df = pd.merge(movies_df,rating_df,on='movieId')

In [10]:
df.shape

(100836, 6)

In [11]:
df.head()

movieId             title                                       genres  \
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
1        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
2        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
3        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
4        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   

   userId  rating   timestamp  
0       1     4.0   964982703  
1       5     4.0   847434962  
2       7     4.5  1106635946  
3      15     2.5  1510577970  
4      17     4.5  1305696483

In [12]:
df.drop(['genres','timestamp'],inplace=True,axis=1)

In [13]:
df.head()

movieId             title  userId  rating
0        1  Toy Story (1995)       1     4.0
1        1  Toy Story (1995)       5     4.0
2        1  Toy Story (1995)       7     4.5
3        1  Toy Story (1995)      15     2.5
4        1  Toy Story (1995)      17     4.5

In [14]:
## Group the Title movies based on no of ratings it has received

In [18]:
combine_ratings = df.groupby('title')['rating'].count().reset_index().rename(columns={'rating':'tot_num_of_ratings'})

In [20]:
rating_with_total_ratings= pd.merge(df,combine_ratings,on='title')

In [21]:
rating_with_total_ratings.head()

movieId             title  userId  rating  tot_num_of_ratings
0        1  Toy Story (1995)       1     4.0                 215
1        1  Toy Story (1995)       5     4.0                 215
2        1  Toy Story (1995)       7     4.5                 215
3        1  Toy Story (1995)      15     2.5                 215
4        1  Toy Story (1995)      17     4.5                 215

In [26]:
rating_with_total_ratings.shape

(100836, 5)

In [27]:
(rating_with_total_ratings['tot_num_of_ratings']>50).shape

(100836,)

In [31]:
rating_with_total_ratings[rating_with_total_ratings['tot_num_of_ratings']>50].shape

(40712, 5)

In [33]:
rating_popular_movie = rating_with_total_ratings[rating_with_total_ratings['tot_num_of_ratings']>50]

In [34]:
rating_popular_movie.shape

(40712, 5)

In [36]:
rating_popular_movie.head(10)

movieId             title  userId  rating  tot_num_of_ratings
0        1  Toy Story (1995)       1     4.0                 215
1        1  Toy Story (1995)       5     4.0                 215
2        1  Toy Story (1995)       7     4.5                 215
3        1  Toy Story (1995)      15     2.5                 215
4        1  Toy Story (1995)      17     4.5                 215
5        1  Toy Story (1995)      18     3.5                 215
6        1  Toy Story (1995)      19     4.0                 215
7        1  Toy Story (1995)      21     3.5                 215
8        1  Toy Story (1995)      27     3.0                 215
9        1  Toy Story (1995)      31     5.0                 215

In [40]:
rating_popular_movie[rating_popular_movie['title']=='Toy Story (1995)'].groupby('title')['rating'].mean()

title
Toy Story (1995)    3.92093
Name: rating, dtype: float64

In [44]:
rating_popular_movie.pivot_table(index='title',columns='userId',values='rating').fillna(0)

userId                             1    2    3    4    5    6    7    8    \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0   
2001: A Space Odyssey (1968)       0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0   
28 Days Later (2002)               0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
300 (2007)                         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...                                ...  ...  ...  ...  ...  ...  ...  ...   
X-Men: The Last Stand (2006)       0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0   
X2: X-Men United (2003)            0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0   
Young Frankenstein (1974)          5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Zombieland (2009)                  0.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0   
Zoolander (2001)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                             9    10   ...  601  602  603  604  605  \
title                                        ...                            
10 Things I Hate About You (1999)  0.0  0.0  ...  0.0  0.0  3.0  0.0  5.0   
12 Angry Men (1957)                0.0  0.0  ...  5.0  0.0  0.0  0.0  0.0   
2001: A Space Odyssey (1968)       0.0  0.0  ...  0.0  0.0  5.0  0.0  0.0   
28 Days Later (2002)               0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
300 (2007)                         0.0  3.0  ...  0.0  0.0  0.0  0.0  3.0   
...                                ...  ...  ...  ...  ...  ...  ...  ...   
X-Men: The Last Stand (2006)       0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
X2: X-Men United (2003)            0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
Young Frankenstein (1974)          0.0  0.0  ...  0.0  0.0  5.0  0.0  0.0   
Zombieland (2009)                  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
Zoolander (2001)                   0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   

userId                             606  607  608  609  610  
title                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  
12 Angry Men (1957)                0.0  0.0  0.0  0.0  0.0  
2001: A Space Odyssey (1968)       5.0  0.0  3.0  0.0  4.5  
28 Days Later (2002)               0.0  0.0  3.5  0.0  5.0  
300 (2007)                         0.0  0.0  5.0  0.0  4.0  
...                                ...  ...  ...  ...  ...  
X-Men: The Last Stand (2006)       0.0  0.0  4.0  0.0  3.0  
X2: X-Men United (2003)            0.0  0.0  4.0  0.0  4.0  
Young Frankenstein (1974)          3.5  0.0  0.0  0.0  0.0  
Zombieland (2009)                  0.0  0.0  0.0  0.0  3.5  
Zoolander (2001)                   0.0  0.0  3.0  0.0  4.0  

[437 rows x 606 columns]

In [45]:
(rating_popular_movie.pivot_table(index='title',columns='userId',values='rating').fillna(0)).shape

(437, 606)

In [46]:
pd.set_option('display.max_columns',None)

In [48]:
rating_popular_movie.pivot_table(index='title',columns='userId',values='rating').fillna(0).head(5)

userId                             1    2    3    4    5    6    7    8    \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0   
2001: A Space Odyssey (1968)       0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0   
28 Days Later (2002)               0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
300 (2007)                         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                             9    10   11   12   13   14   15   16   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0   
2001: A Space Odyssey (1968)       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
28 Days Later (2002)               0.0  0.0  0.0  0.0  0.0  0.0  3.5  0.0   
300 (2007)                         0.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                             17   18   19   20   21   22   23   24   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  5.0  0.0  0.0  0.0  0.0  3.0  0.0   
2001: A Space Odyssey (1968)       0.0  4.0  3.0  0.0  0.0  0.0  4.0  0.0   
28 Days Later (2002)               0.0  0.0  0.0  0.0  0.0  1.5  0.0  0.0   
300 (2007)                         0.0  3.5  0.0  0.0  3.5  0.0  0.0  4.0   

userId                             25   26   27   28   29   30   31   32   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2001: A Space Odyssey (1968)       0.0  0.0  2.0  3.0  5.0  0.0  0.0  0.0   
28 Days Later (2002)               0.0  0.0  0.0  3.0  4.5  0.0  0.0  0.0   
300 (2007)                         0.0  0.0  0.0  4.5  0.0  0.0  0.0  0.0   

userId                             33   34   35   36   37   38   39   40   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2001: A Space Odyssey (1968)       0.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0   
28 Days Later (2002)               0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
300 (2007)                         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                             41   42   43   44   45   46   47   48   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  0.0  0.0  0.0  0.0  2.5  0.0   
2001: A Space Odyssey (1968)       2.0  5.0  0.0  0.0  4.0  0.0  0.0  0.0   
28 Days Later (2002)               0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
300 (2007)                         2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                             49   50   51   52   54   55   56   57   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2001: A Space Odyssey (1968)       0.0  4.5  5.0  0.0  0.0  0.0  0.0  5.0   
28 Days Later (2002)               0.0  0.0  5.0  0.0  0.0  0.0  0.0  0.0   
300 (2007)                         0.0  0.0  5.0  5.0  0.0  0.0  0.0  0.0   

userId                             58   59   60   61   62   63   64   65   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  0

In [51]:
movie_features_df =rating_popular_movie.pivot_table(index='title',columns='userId',values='rating').fillna(0)

In [49]:
from scipy.sparse import csr_matrix

In [52]:
csr_matrix(movie_features_df.values)

<437x606 sparse matrix of type '<class 'numpy.float64'>'
	with 40710 stored elements in Compressed Sparse Row format>

In [53]:
movie_features_df_matrix = csr_matrix(movie_features_df.values)

In [54]:
movie_features_df_matrix

<437x606 sparse matrix of type '<class 'numpy.float64'>'
	with 40710 stored elements in Compressed Sparse Row format>

In [55]:
from sklearn.neighbors import NearestNeighbors

In [56]:
model_knn =NearestNeighbors(metric='cosine',algorithm='brute')

In [57]:
model_knn.fit(movie_features_df_matrix)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [59]:
movie_features_df.head(2)

userId                             1    2    3    4    5    6    7    8    \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0   

userId                             9    10   11   12   13   14   15   16   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0   

userId                             17   18   19   20   21   22   23   24   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  5.0  0.0  0.0  0.0  0.0  3.0  0.0   

userId                             25   26   27   28   29   30   31   32   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                             33   34   35   36   37   38   39   40   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                             41   42   43   44   45   46   47   48   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  0.0  0.0  0.0  0.0  2.5  0.0   

userId                             49   50   51   52   54   55   56   57   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                             58   59   60   61   62   63   64   65   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  3.0  0.0  5.0  4.0  5.0  0.0   

userId                             66   67   68   69   70   71   72   73   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  4.5  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                4.5  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                             74   75   76   77   78   79   80   81   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                             82   83   84   85   86   87   88   89   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  4.0  0.0  0.0  0.0  0.0  0.0   

userId                             90   91   92   93   94   95   96   97   \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  5.0  0.0  0.0  0.0  0.0  0.0   
12 Angry Men (1957)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                             98   99   100  101  102  103  104  105  \
title                                                                       
10 Things I Hate About You (1999)  0.0  0.0  0.0  0.0  0.0  0.0  5.0  0.0   
12 Angry Men (1957)                0.0  0.0  4.0  0.0  0.0  0

In [61]:
movie_features_df_matrix[0].todense()

matrix([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 5. , 0. ,
         0. , 0. , 0. , 0. , 0. , 3. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
         0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
         0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
         0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
         0. , 4.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
         0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 5. ,
         0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 5. , 0. ,
         0. , 0. , 0. , 0. , 0. , 4. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
         0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
         4. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
         0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. ,
         3.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
         0. , 0. , 0. , 0. , 0. , 4.5,

In [63]:
movie_features_df.shape[0]

437

In [64]:
movie_features_df.shape

(437, 606)

In [66]:
np.random.choice(movie_features_df.shape[0])

<IPython.core.display.Javascript object>

272

In [67]:
np.random.choice(movie_features_df.shape[0])

<IPython.core.display.Javascript object>

76

In [68]:
query_index = np.random.choice(movie_features_df.shape[0])

<IPython.core.display.Javascript object>

In [69]:
query_index

390

In [70]:
movie_features_df.iloc[query_index,:]

userId
1      0.0
2      0.0
3      0.0
4      4.0
5      0.0
      ... 
606    0.0
607    0.0
608    2.0
609    0.0
610    0.0
Name: This Is Spinal Tap (1984), Length: 606, dtype: float64

In [72]:
movie_features_df.iloc[query_index,:].values.reshape(-1,1)

array([[0. ],
       [0. ],
       [0. ],
       [4. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [5. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [5. ],
       [4.5],
       [0. ],
       [5. ],
       [0. ],
       [0. ],
       [0. ],
       [4. ],
       [0. ],
       [0. ],
      

In [74]:
movie_features_df.iloc[query_index,:].values.reshape(1,-1)

array([[0. , 0. , 0. , 4. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 5. , 0. , 0. , 0. , 0. , 0. , 5. , 4.5, 0. , 5. ,
        0. , 0. , 0. , 4. , 0. , 0. , 0. , 0. , 0. , 4. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 4. , 0. , 0. , 0. , 0. , 3.5, 0. , 3.5, 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 2. , 0. , 0. , 4. , 4. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 3.5,
        0. , 0. , 0. , 0. , 0. , 5. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 4. , 0. ,
        0. , 0. , 4. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 4. , 0. ,
        0. , 0. , 0. , 0. , 0. , 3.5, 0. , 0. , 0. 

In [75]:
distances, indices = model_knn.kneighbors(movie_features_df.iloc[query_index,:].values.reshape(1,-1)  , n_neighbors=6)

In [76]:
distances

array([[0.        , 0.48480283, 0.48805147, 0.49566824, 0.51460148,
        0.5236431 ]])

In [77]:
indices

array([[390, 272, 155, 318, 147,  49]], dtype=int64)

In [94]:
movie_features_df.iloc[390,:]

userId
1      0.0
2      0.0
3      0.0
4      4.0
5      0.0
      ... 
606    0.0
607    0.0
608    2.0
609    0.0
610    0.0
Name: This Is Spinal Tap (1984), Length: 606, dtype: float64

In [95]:
movie_features_df.iloc[272,:]

userId
1      5.0
2      0.0
3      0.0
4      5.0
5      0.0
      ... 
606    4.0
607    0.0
608    3.0
609    0.0
610    5.0
Name: Monty Python and the Holy Grail (1975), Length: 606, dtype: float64

In [108]:
movie_features_df.index[272]

'Monty Python and the Holy Grail (1975)'

In [109]:
movie_features_df.index[155]

'Fish Called Wanda, A (1988)'

In [96]:
distances

array([[0.        , 0.48480283, 0.48805147, 0.49566824, 0.51460148,
        0.5236431 ]])

In [97]:
distances.flatten()

array([0.        , 0.48480283, 0.48805147, 0.49566824, 0.51460148,
       0.5236431 ])

In [98]:
movie_features_df.index[query_index]

'This Is Spinal Tap (1984)'

In [107]:
for i in range(len(distances.flatten())):
    if i==0:
        print("Recommendations for {0} : \n".format(movie_features_df.index[query_index]))
    
    else:
        print("{0}:{1}, with distance of {2}".format(i,movie_features_df.index[indices.flatten()[i]],distances.flatten()[i]))

Recommendations for This Is Spinal Tap (1984) : 

1:Monty Python and the Holy Grail (1975), with distance of 0.4848028275102515
2:Fish Called Wanda, A (1988), with distance of 0.4880514743117226
3:Raising Arizona (1987), with distance of 0.4956682388740167
4:Ferris Bueller's Day Off (1986), with distance of 0.5146014839442545
5:Beetlejuice (1988), with distance of 0.5236431012871172
