In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('D:\ML\Krish Naik Codes\Codebasics\datasets\homeprices_onehotencoding.csv')

In [4]:
df.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

## One hot encoding using get_dummies

In [7]:
town =pd.get_dummies(df['town'],drop_first=True)

In [11]:
df1=pd.concat([df,town],axis=1)

In [12]:
df1.head()

town  area   price  robinsville  west windsor
0  monroe township  2600  550000            0             0
1  monroe township  3000  565000            0             0
2  monroe township  3200  610000            0             0
3  monroe township  3600  680000            0             0
4  monroe township  4000  725000            0             0

In [14]:
df1.drop('town',inplace=True,axis=1)

In [15]:
df1.head()

area   price  robinsville  west windsor
0  2600  550000            0             0
1  3000  565000            0             0
2  3200  610000            0             0
3  3600  680000            0             0
4  4000  725000            0             0

In [16]:
X=df1[['area','robinsville','west windsor']]
y=df1['price']

In [19]:
X=X.values
y=y.values

In [20]:
from sklearn.linear_model  import LinearRegression
lr =LinearRegression()

In [22]:
lr.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [23]:
lr.coef_

array([  126.89744141, 25686.4115244 , 40013.97548914])

In [24]:
lr.intercept_

209776.39217373315

In [29]:
lr.predict([[4000,0,0]])

array([717366.15781552])

In [30]:
(126.89744141*4000)+(25686.4115244*0)+(40013.97548914*0)+209776.39217373315

717366.1578137332

In [33]:
lr.score(X,y)

0.9573929037221871

## One hot encoding using LabelEncoder

In [34]:
df.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
le =LabelEncoder()

In [38]:
le.fit_transform(df['town'])

array([0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1])

In [39]:
df['town']=le.fit_transform(df['town'])

In [41]:
df.head(8)

town  area   price
0     0  2600  550000
1     0  3000  565000
2     0  3200  610000
3     0  3600  680000
4     0  4000  725000
5     2  2600  585000
6     2  2800  615000
7     2  3300  650000

In [42]:
X=df[['area','town']].values
y=df['price'].values

In [43]:
from sklearn.linear_model import LinearRegression
lr =LinearRegression()

In [44]:
lr.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [45]:
lr.score(X,y)

0.9552018104317442

## One hot encoding using One Hot Encoding

In [47]:
df=pd.read_csv('D:\ML\Krish Naik Codes\Codebasics\datasets\homeprices_onehotencoding.csv')

In [48]:
df.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [83]:
X=df[['town','area']].values
y=df['price'].values

In [86]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [87]:
ohe = OneHotEncoder(categorical_features=[0])

ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')