In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt


In [3]:
digits = load_digits()

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

### Logistic Regression

In [5]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9611111111111111

### SVM

In [6]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.4685185185185185

### Random Forest

In [7]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9796296296296296

### KFold cross validation allows us to evaluate performance of a model by creating K folds of given dataset. This is better then traditional train_test_split. In this tutorial we will cover basics of cross validation and kfold. We will also look into cross_val_score function of sklearn library which provides convenient way to run cross validation on a model

In [9]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [13]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [14]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=2)

In [15]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[5 6 7 8] [0 1 2 3 4]
[0 1 2 3 4] [5 6 7 8]


In [16]:
def get_score(model,X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [20]:
get_score(LogisticRegression(),X_train,X_test, y_train, y_test)

D:\AnacondaDistribution\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\AnacondaDistribution\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.9611111111111111

In [21]:
get_score(SVC(),X_train,X_test, y_train, y_test)

D:\AnacondaDistribution\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.4685185185185185

In [22]:
get_score(RandomForestClassifier(),X_train,X_test, y_train, y_test)

D:\AnacondaDistribution\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.9518518518518518

In [24]:
## so we have seen above how each of the models would have behaved with our custom function

## Stratified CV

In [25]:
from sklearn.model_selection import StratifiedKFold

In [26]:
folds =StratifiedKFold(n_splits=3)

In [28]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index,test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [29]:
scores_logistic

[0.8953488372093024, 0.9499165275459098, 0.9093959731543624]

In [30]:
np.mean(scores_logistic)

0.9182204459698582

In [31]:
scores_svm

[0.39368770764119604, 0.41068447412353926, 0.4597315436241611]

In [32]:
scores_rf

[0.9285714285714286, 0.9465776293823038, 0.9295302013422819]

In [34]:
print('Logistic Regression score - {} || SVM Score- {} || Random Forest score - {}'.format(np.mean(scores_logistic),
                                                                                            np.mean(scores_svm),
                                                                                            np.mean(scores_rf)))

Logistic Regression score - 0.9182204459698582 || SVM Score- 0.4213679084629655 || Random Forest score - 0.9348930864320047


## We can use the KFold without defing the function

## cross_val_score

In [35]:
from sklearn.model_selection import cross_val_score

In [40]:
lr_score = cross_val_score(lr,X_train,y_train , cv=3)

In [41]:
lr_score

array([0.89851485, 0.89276808, 0.92676768])

In [42]:
svm_score = cross_val_score(svm,X_train,y_train , cv=3)

In [43]:
svm_score

array([0.35643564, 0.33915212, 0.30050505])

In [44]:
rf_score = cross_val_score(rf,X_train,y_train , cv=3)

In [45]:
rf_score

array([0.88613861, 0.88279302, 0.92424242])

In [46]:
print('Logistic Regression score - {} || SVM Score- {} || Random Forest score - {}'.format(np.mean(lr_score),
                                                                                            np.mean(svm_score),
                                                                                            np.mean(rf_score)))

Logistic Regression score - 0.906016869351108 || SVM Score- 0.33203093792338506 || Random Forest score - 0.8977246851867231


## Parameter tunning using k fold cross validation

In [47]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8865020758582511

In [48]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9332835573554096

In [49]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9527773592811059

In [50]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9543719277129623