In [57]:
import pandas as pd
import numpy as np

In [58]:
df=pd.read_csv('D:\ML\Krish Naik Codes\Codebasics\datasets\hiring.csv')

In [59]:
df.head(10)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [60]:
int_score=int(df['test_score(out of 10)'].median())

In [61]:
df['test_score(out of 10)'].fillna(int_score,inplace=True)

In [62]:
df['experience'].fillna('zero',inplace=True)

In [63]:
from word2number import w2n

In [64]:
df['experience']

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [65]:
for i in range(len(df)):
    df['experience'][i]=w2n.word_to_num(str(df['experience'][i]))

D:\AnacondaDistribution\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [66]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          0                    8.0                           9      50000
1          0                    8.0                           6      45000
2          5                    6.0                           7      60000
3          2                   10.0                          10      65000
4          7                    9.0                           6      70000

In [70]:
from sklearn.preprocessing import MinMaxScaler

In [69]:
X=df[['experience','test_score(out of 10)','interview_score(out of 10)']]
y=df['salary($)']

In [72]:
scaler =MinMaxScaler()

In [73]:
scaler.fit(X)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [74]:
scaler.transform(X)

array([[0.        , 0.5       , 0.75      ],
       [0.        , 0.5       , 0.        ],
       [0.45454545, 0.        , 0.25      ],
       [0.18181818, 1.        , 1.        ],
       [0.63636364, 0.75      , 0.        ],
       [0.27272727, 0.25      , 1.        ],
       [0.90909091, 0.5       , 0.25      ],
       [1.        , 0.25      , 0.5       ]])

In [77]:
X=scaler.transform(X)

In [75]:
from sklearn.linear_model import LinearRegression

In [76]:
lr =LinearRegression()

In [79]:
lr.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [80]:
lr.predict([[0.        , 0.5       , 0.75]])

array([52350.0727802])

In [82]:
lr.predict([[0.45454545, 0.        , 0.25  ]])

array([58312.95473563])

## Save the model to pickle format

In [83]:
import pickle

In [84]:
with open('D:\ML\Krish Naik Codes\Codebasics\model_pickle','wb') as f:
    pickle.dump(lr,f)

In [85]:
with open('D:\ML\Krish Naik Codes\Codebasics\model_pickle','rb') as f:
    new_model= pickle.load(f)

In [86]:
new_model.predict([[0.45454545, 0.        , 0.25  ]])

array([58312.95473563])

In [87]:
## So we have used the pickle file to save the model and re-use the model again

## 2nd option - sklearn.joblib

In [88]:
from sklearn.externals import joblib

In [91]:
joblib.dump(lr,'joblib_model')

['joblib_model']

In [92]:
new_model_2= joblib.load('joblib_model')

In [93]:
new_model.predict([[0.45454545, 0.        , 0.25  ]])

array([58312.95473563])

In [94]:
## so we got the same predicted value